### PR TITLE
Proposed fix for issue # 19

### PR DESCRIPTION
**Pull request by jlredd**
Simply added .js extension to flyway in bin folder. Adjusted package.json to correctly reference the js file.

### CODE REVIEW

**Comment by markgardner** [comment]
Does this break the ability for the package to be installed globally and executed from the terminal?

**Comment by jlredd** [comment]
Yes, both a global install and per project installation are having this error.

**Comment by markgardner** [comment]
I'm down with merging this PR, just need to get the fork changes reverted. Sorry for the delay. Been a crazy week.

**Comment by markgardner** [comment]
I went ahead and made the change d80e8356cdb57d5660a99220c457a83fae00188a

**Pull request closed without merging**
